### ISSUE TITLE
Want to view previous revision content of a document

### ISSUE THREAD

**Issue by BeatriceThalo** [apache/couchdb-fauxton#1069]
Creating an issue for this SO post with images. https://stackoverflow.com/questions/41464410/couchdb-fauxton-how-to-navigate-through-revisions-history

## Expected Behavior
When using CouchDB 1.6.1 there was a Previous Revision clickable in the footer while viewing a document.

## Current Behavior
Can't view previous revisions of a document.

## Possible Solution
In the SO's comments, there is a task to see the whole rev tree. That is not needed/overkill for this request.

## Steps to Reproduce (for bugs)
See images in SO post.

## Context
Our staging server uses 1.6.1 and our production server uses 2.1.0. If our modifying client code is upserting or otherwise behaving incorrectly, we'd like to view the previous data in this backdoor way for faster "search and rescue" for seemingly lost data.

## Your Environment
* Version used: Fauxton on  Apache CouchDB v. 2.1.0
* Browser Name and version: Firefox 57.0.4 (64-bit) for Ubuntu or Chrome 65.0.3325.162
* Operating System and version (desktop or mobile): Ubuntu 17.04

**Comment by popojargo** [comment]
Adding a component to visual revision tree could be interesting.
From what Jan told me, he was not in favor of bringing back the revision browser.

**Comment by wohali** [comment]
@BeatriceThalo what is your intended use of this feature? I am concerned about your reliance on it.

The reason for the resistance is that prior "revisions" shouldn't be relied upon to exist at all. This behaviour changed with 2.0. 

Prior "revisions" exist only as a means to an end - consistent replication. Compaction (and the automatic compaction daemon) or replication can remove them at any time.

CouchDB isn't a version control tool; if you need to ensure access to "prior revisions" of a document, you must store them as different documents.

I'm pretty sure @janl and I would both be +1 on a button to click that shows all conflicted versions of a document, though.

**Comment by popojargo** [comment]
@wohali We already have a "Conflicts" button that shows when a document has conflicts. It includes a revision browser and you can go through the revision and change the selected Winner.

**Comment by BeatriceThalo** [comment]
@wohali You make a great point. Maybe my application should look into using version control for that. @popojargo Yes the conflicts button (and icon in Table view) is a great feature (that 1.6.1 doesn't have).

**Comment by wohali** [comment]
Thanks @BeatriceThalo . With your permission, I'd like to close this ticket (along with https://issues.apache.org/jira/browse/COUCHDB-2163) as `wontfix` for future reference, so people understand the decision making process here.

I'd could see visualisation (as proposed in COUCHDB-2163) return for _conflicted_ documents, that'd be interesting.

**Comment by ahayes** [comment]
Every time I see the devs squash someone's desire to make use of revisions (and I have seen it a lot), I can't help but wonder why this couldn't be a killer feature of CouchDB. I understand that for performance reasons on huge databases, compaction can be a good thing. But I have many databases of 10s of thousands of records that have run for years without compaction and being able to see and use the revision history is great. In fact, I wish I could have older revisions replicate too. A replicating document oriented database able to serve dependable previous versions of documents using the same uuid to reference them would be great. Just pass a revision number or leave off for latest.

When there is a fear of a bunch of people coming to depend on something, it is a pretty good sign that you have made something that has valuable uses you didn't imagine. Those uses could potentially be embraced instead of being dismissed/blocked.

Anyway, I have to assume there is some big technical reason not to do it because otherwise, why not? If there is somewhere better to document the bigger discussion (or if it already exists) let me know and I will take it there. :)

**Comment by wohali** [comment]
@ahayes the best place to look is the user and dev mailing list archives. this has come up countless times before - you'll want to start searching back in 2009 or so for the first instances of the discussion.

Archives are at https://lists.apache.org/list.html?couchdb.apache.org

**Comment by kstankov** [comment]
For us it is VERY frustrating that this feature is missing from Fauxton and we will probably need to make our own visual tool, or dump CouchDB. Why would you have revisions at the heart of the product, and then explain why you should not use them??? 
I have built an entire product based on CouchDB revisions!
And, please, don't warn about compaction, as it is us who decide when and how and if to run a compaction.
In addition, the fix looks so easy that I'm thrilled to understand why it would be closed as wontfix...

**Comment by sudeepdk** [comment]
```
to get list of all revisions.
https://docs.couchdb.org/en/stable/api/document/common.html#getting-a-list-of-revisions



to view specific version of document.
https://docs.couchdb.org/en/stable/api/document/common.html#obtaining-a-specific-revision

```

**Comment by DarrenCook** [comment]
+1 to the original request. @sudeepdk Those are curl commands, which was exactly @kstankov 's point: "we will probably need to make our own visual tool, or dump CouchDB". Why force everyone to reinvent that wheel? (As far as I can tell the functionality is being deliberately excluded, and is already there for conflicts, so it is not a case of no-one having time to work on it.)

My primary use for Fauxton is troubleshooting, checking the DB during development, and so on. I doubt that is atypical.

**Comment by davisp** [comment]
I just stumbled across this and figured I'd give a bit more background on the `_rev` field and why its not suitable as a revision controls system.

First, its been a very common misconception for basically the entire history of CouchDB that the `_rev` field and the associated revision tree are useful as a revision control field. There have been numerous discussions over the years on completely renaming these concepts to avoid precisely this confusion. Unfortunately the names are baked directly into the replication protocol so they would require some fairly massive investment to rename. That's definitely on us as a project and we should have started years ago to make that transition. Unfortunately, that doesn't help the current situation.

The reason that the `_rev` field is not useful as a revision control system is due to the nature of replication itself. The replicator and replication protocol never transfer document data related to internal nodes of the revision tree. In any situation where replication is involved the contents of older revisions may or may not exist. Thus depending on them to exist will inevitably lead to confusion and assertions that CouchDB is broken when they've gone missing.

The reason that we made the UI change for CouchDB 2.0 is because replication is fundamental to the design of CouchDB's clustering logic. If you were to attempt to implement this feature you would end up in a situation where it was roughly random on whether the links worked correctly even so far as having document bodies appearing and disappearing with a page refresh. There are a number of factors that would contribute to this that would not be easily overcome with the eventual consistency design of CouchDB clustering. Everything from uncoordinated compaction events (i.e., all nodes in a cluster may compact any shard at any time) to parallel updates causing some nodes to miss a revision between internal replication updates (at which point a node will have never seen an internal revision and replication will never transfer it). And then finally to replication from remote nodes that never transfer old revision bodies to begin with which leads to confusion when an old revision is available on one side of the replication but not the other.

And preemptively, the answer to: "Well, why not just enhance the replicator to transfer some number of previous revision bodies?", there are two main reasons. Primarily and easiest to explain is that the replicator has never supported this which means making the change would be even harder than us just changing the concept names to something less easily confused rather than update the algorithmic aspects of the replicator. Secondly and more importantly, it doesn't actually fix anything. Having a configurable number of revisions just means that our hard coded value of 1 document body per leaf would be some larger number. The underlying issues about missing revisions doesn't change any of the fundamental issues in attempting to rely on previous revision data.

Hopefully that clarifies why adding this sort of feature isn't possible. I do understand that the `_rev` token can be easily misunderstood as a useful approach for revision history. However, there are fundamental aspects to CouchDB that prevent it from being used as such.

**Comment by DarrenCook** [comment]
> not suitable as a revision controls system.

I can only speak for myself, but it is not a desire to have a revision control system. I think we understand the revisions might be compacted away, or be unreliable for other reasons.

I just want to be able to diff with the previous revision, when I know it is there,*using Fauxton*, where I am already logged in, rather than having to mess around with using curl. I.e. for developer productivity and for a more pleasurable developer experience (visual diffs are more pleasant than text diffs in the console).

The most recent case where I needed this, that prompted my comment: I was testing a DB initialization script, and viewing the result in Fauxton, and it was showing all docs with a rev of "1-xxx", except for one, which was showing "2-xxx". I wanted to see what it's "1-xxx" was, to see if this made sense or if it was a bug.  (Spoiler: It was a bug in my script.)

**Comment by wohali** [comment]
part of @davisp 's comment is relevant here:

>If you were to attempt to implement this feature you would end up in a situation where it was roughly random on whether the links worked correctly even so far as having document bodies appearing and disappearing with a page refresh.

is key to understanding this. If you're in a cluster there's no guarantee that all nodes are consistent on previous versions. We can't special case Fauxton for this specific need.

Further, see https://github.com/apache/couchdb/issues/2368 which says:

> I should also point out that in the 4.0 release there won't be a compaction process at all -- old document revisions will be removed immediately when the new update is committed.

4.0 is just around the corner.
