### ISSUE TITLE
[Dev tools] Upgrade docker image

### ISSUE THREAD

**Issue by popojargo** [apache/couchdb-fauxton#1077]
We currently use CouchDB 2.0.0 in the repo. I will update to use the latest image because we can't test latest feature.

**Comment by popojargo** [comment]
@wohali Where are the couchdbdev docker images coming from? Are you aware if we have a repository where I can look  for that?

**Comment by wohali** [comment]
@popojargo you don't want the couchdbdev docker images, because those don't actually have CouchDB in them - just a suitable build environment. (They are built from instructions in apache/couchdb-ci, and are currently under major rework to support Ubuntu 18.10.)

You want apache/couchdb-docker and either the 2.1.1 or the dev image. These are the source of the official couchdb docker image. Unfortunately, right now the dev image is intentionally not published because of ASF policy. I am working on a way to share this within the CouchDB community for CI purposes (i.e. a private Docker repository), but it is slow going.
